name: CD - Build & Push Docker Images

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ðŸ”‘ Convert repo owner to lowercase
      - name: Set lowercase repo owner
        run: |
          echo "OWNER_LOWER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & push backend image
        run: |
          docker build -t ghcr.io/$OWNER_LOWER/notes-backend:${{ github.ref_name }} ./backend
          docker push ghcr.io/$OWNER_LOWER/notes-backend:${{ github.ref_name }}

      - name: Build & push frontend image
        run: |
           docker build \
            --build-arg VITE_API_URL=/api \
            -t ghcr.io/$OWNER_LOWER/notes-frontend:${{ github.ref_name }} ./frontend
          docker push ghcr.io/$OWNER_LOWER/notes-frontend:${{ github.ref_name }}
